# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoscaleAsignment' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'Charts'

# Pods for GoscaleAsignment

target 'GoscaleAsignmentTests' do
inherit! :search_paths
# Pods for testing
end

target 'GoscaleAsignmentUITests' do
inherit! :search_paths
# Pods for testing
end

end
